---
title: "project01"
author: "Dante Ramirez/Mina Mehdinia/Niloufar Saririan/John-Paul Quiñones"
date: '2022-08-08'
output: html_document
---

```{r libraries and data, message = F, warning = F}

# Loads packages for tidying and regression
library(tidyverse)
library(lubridate)
library(ISLR2)
library(MASS)
library(readxl)
library(kableExtra)
library(table1)
library(mice)
library(ggpubr)
library(knitr)
library(magrittr)
library(gridExtra)
library(forestplot)


# Loads libraries
main_stress_df <- read_excel("data/StatsProjectData.xlsx")
pstress_df <- as.data.frame(  read_csv("data/PSTRESS_covar.csv") )
GA_df <- read_csv("data/GA.csv")
EMA_df <- read_csv("data/diarycomplete01132018.csv")
one_heart_data_test_df <- read_csv("data/Actiheart Cleaned/actiheart_1003_G3.csv")

# Removes all columns which contain categories rather than numerics
EMA_num <- EMA_df %>% subset(select = -c(10:24, 31:33, 35:43, 45:48))

# Gets rid NA's and duplicates based on ID, day, and time
EMA_num <- EMA_num %>% 
            subset(!is.na(EMA_num[,56])) %>%
            distinct(Idmaternal,
                     Day,
                     finish.time,
                     elapsed.time.sec,
                     .keep_all = T)
  
# Prepares data for joining

# Renames bmi variable the same in both dfs
main_stress_df <- main_stress_df %>% 
                    rename(bmi_prepregMaternalDemographics = bmi_prepreg)

# Makes bmi rounded in both dfs
main_stress_df$bmi_prepregMaternalDemographics <- as.numeric(main_stress_df$bmi_prepregMaternalDemographics)
main_stress_df$bmi_prepregMaternalDemographics <- round(main_stress_df$bmi_prepregMaternalDemographics,
                                                        digits = 2)
# Gets rid of rows in pstress_df that are nonexistant in main_stress_df
pstress_df_drop <- pstress_df %>% subset(ID != 1131) %>%
                                  subset(ID != 1233) %>%
                                  subset(ID != 1156) %>%
                   mutate(t0_parity = as.character(t0_parity))

# Joins both stress data frames
stress_df <- inner_join(pstress_df_drop, main_stress_df) %>%
              subset(select = -c(12)) %>%
              rename(Idmaternal = ID)

```

```{r visit RMSSD data frames}

set.seed(4)

# modify EMA_num data frame -----------------------------------------------
# EMA_num needs to be modified to exclude NA Trimester and NA Day
# then when calculating RMSSD, skip the NA values on StressNumeric
EMA_num <- EMA_num %>%
  filter(!is.na(Trimester),
         !is.na(Day)) %>%
  dplyr::select(Idmaternal,
                Trimester,
                Day,
                StressedNumeric,
                PercievedStressScore,
                PositiveMoodScore,
                NegativeMoodScore)

# another way of calculating RMSSD by ID, Trimester, and Day --------------
rslt <- EMA_num %>%
  group_by(Idmaternal, Trimester, Day) %>%
  summarise(
    rmssd_stress_num = sqrt(sum(diff(StressedNumeric[!is.na(StressedNumeric)])^2) /
      (length(StressedNumeric[!is.na(StressedNumeric)]) - 1)),
    mean_stress_num = mean(StressedNumeric),
    rmssd_pss = sqrt(sum(diff(PercievedStressScore[!is.na(PercievedStressScore)])^2) /
      (length(PercievedStressScore[!is.na(PercievedStressScore)]) - 1)),
    mean_pss = mean(PercievedStressScore),
    rmssd_positive = sqrt(sum(diff(PositiveMoodScore[!is.na(PositiveMoodScore)])^2) /
      (length(PositiveMoodScore[!is.na(PositiveMoodScore)]) - 1)),
    mean_postive = mean(PositiveMoodScore),
    rmssd_negative = sqrt(sum(diff(NegativeMoodScore[!is.na(NegativeMoodScore)])^2) /
      (length(NegativeMoodScore[!is.na(NegativeMoodScore)]) - 1)),
    mean_negative = mean(NegativeMoodScore)
  )

# Group day RMSSD by ID and visit to give visit RMSSD for each id
visit_RMSSD_df <- rslt %>% 
                  group_by(Idmaternal, Trimester) %>% 
                  summarise(visit_RMSSD_stress_num = mean(rmssd_stress_num),
                            mean_stressNum = mean(mean_stress_num),
                            visit_RMSSD_pss = mean(rmssd_pss),
                            meanPss = mean(mean_pss),
                            visit_RMSSD_positive = mean(rmssd_positive),
                            meanPositive = mean(mean_postive),
                            visit_RMSSD_negative = mean(rmssd_negative),
                            meanNegative = mean(mean_negative)) %>%
                  mutate(Trimester = as.factor(Trimester)) %>%
                  pivot_wider(names_from = Trimester,
                              values_from = c(visit_RMSSD_stress_num,
                                              mean_stressNum,
                                              visit_RMSSD_pss,
                                              meanPss,
                                              visit_RMSSD_positive,
                                              meanPositive,
                                              visit_RMSSD_negative,
                                              meanNegative))

# Data frame for our line plots
line_plot_df <- rslt %>%
                group_by(Idmaternal) %>%
                mutate(counter = rep(1:length(rmssd_stress_num))) %>%
                mutate(Idmaternal = as.factor(Idmaternal)) %>%
                filter(Idmaternal %in% sample(levels(Idmaternal), size = 3))

```



```{r graphics and plots}

# Plot of correlation between visit 0 RMSSD and visit 1 RMSSD in stress numeric
vis0_vis1plot <- ggplot(data = visit_RMSSD_df,
                        mapping = aes(x = visit_RMSSD_stress_num_0,
                        y = visit_RMSSD_stress_num_1)) +
                  geom_point() +
                  geom_abline(slope= 1,
                              intercept = 0,
                              color = "red",
                              linetype = 2) +
                  theme_bw(base_size = 14) +
                  labs(title = "Correlation between Visit 0 and Visit 1 RMSSD, Stress Numeric",
                  x = "RMSSD Visit 0 StressNumeric",
                  y = "RMMSD Visit 1 StressNumeric") +
                  theme(plot.title = element_text(hjust = 0.5,
                                                  face = "bold",
                                                  size = 14)) +
                  stat_cor(method = "spearman", label.x = 1.6, label.y = 1.5)

vis0_vis1plot

# Plot of correlation between visit 0 RMSSD and visit 1 RMSSD in stress numeric
vis1_vis2plot <- ggplot(data = visit_RMSSD_df,
                        mapping = aes(x = visit_RMSSD_stress_num_1,
                        y = visit_RMSSD_stress_num_2)) +
                  geom_point() +
                  geom_abline(slope= 1,
                              intercept = 0,
                              color = "red",
                              linetype = 2) +
                  theme_bw(base_size = 14) +
                  labs(title = "Correlation between Visit 1 and Visit 2 RMSSD, Stress Numeric",
                  x = "RMSSD Visit 1 StressNumeric",
                  y = "RMMSD Visit 2 StressNumeric") +
                  theme(plot.title = element_text(hjust = 0.5,
                                                  face = "bold",
                                                  size = 14)) +
                  stat_cor(method = "spearman", label.x = 1.3, label.y = 1.9)

vis1_vis2plot

# Distribution of RMSSD
vis0_hist <- ggplot(data = visit_RMSSD_df,
                        mapping = aes(x = visit_RMSSD_stress_num_0)) +
                  geom_histogram(color = "black") +
                  theme_bw(base_size = 16) +
                  labs(title = "Distribution of Visit-0 RMSSD",
                  x = "RMSSD-0",
                  y = "Count") +
                  theme(plot.title = element_text(hjust = 0.5,
                                                  face = "bold",
                                                  size = 14))

vis0_hist

# Line plots to show change in daily RMSSD over time
RMSSD_line_plot <- ggplot(data = line_plot_df,
                          mapping = aes(x = counter,
                                        y = rmssd_stress_num,
                                        group = Idmaternal,
                                        color = Idmaternal)) +
                   geom_line() +
                   scale_x_continuous(name = "Visit",
                                      breaks = c(2, 6, 10),
                                      labels = c("1",
                                                 "2",
                                                 "3")) +
                  labs(y = "RMSSD") +
                  theme_classic(base_size = 14) +
                  geom_vline(xintercept = 4, 
                             color = "red",
                             linetype = 2,
                             alpha = .5) + 
                  geom_vline(xintercept = 8, 
                             color = "red",
                             linetype = 2,
                             alpha = .5)
  

RMSSD_line_plot

```

```{r change in RMSSD}

stress_num_0_1 <- visit_RMSSD_df$visit_RMSSD_stress_num_0 - visit_RMSSD_df$visit_RMSSD_stress_num_1

stress_num_0_2 <- visit_RMSSD_df$visit_RMSSD_stress_num_0 - visit_RMSSD_df$visit_RMSSD_stress_num_2

stress_num_1_2 <- visit_RMSSD_df$visit_RMSSD_stress_num_1 - visit_RMSSD_df$visit_RMSSD_stress_num_2

pss_0_1 <- visit_RMSSD_df$visit_RMSSD_pss_0 - visit_RMSSD_df$visit_RMSSD_pss_1

pss_0_2 <- visit_RMSSD_df$visit_RMSSD_pss_0 - visit_RMSSD_df$visit_RMSSD_pss_2

pss_1_2 <- visit_RMSSD_df$visit_RMSSD_pss_1 - visit_RMSSD_df$visit_RMSSD_pss_2

positive_0_1 <- visit_RMSSD_df$visit_RMSSD_positive_0 - visit_RMSSD_df$visit_RMSSD_positive_1

positive_0_2 <- visit_RMSSD_df$visit_RMSSD_positive_0 - visit_RMSSD_df$visit_RMSSD_positive_2

positive_1_2 <- visit_RMSSD_df$visit_RMSSD_positive_1 - visit_RMSSD_df$visit_RMSSD_positive_2

negative_0_1 <- visit_RMSSD_df$visit_RMSSD_negative_0 - visit_RMSSD_df$visit_RMSSD_negative_1

negative_0_2 <- visit_RMSSD_df$visit_RMSSD_negative_0 - visit_RMSSD_df$visit_RMSSD_negative_1

negative_1_2 <- visit_RMSSD_df$visit_RMSSD_negative_1 - visit_RMSSD_df$visit_RMSSD_negative_2

pairwise_RMSSD_df <- data.frame(stress_num_0_1,
                                stress_num_0_2,
                                stress_num_1_2,
                                pss_0_1,
                                pss_0_2,
                                pss_1_2,
                                positive_0_1,
                                positive_0_2,
                                positive_1_2,
                                negative_0_1,
                                negative_0_2,
                                negative_1_2)

sum_vec <- c()

for(i in 1:12){
  
  sum_vec[i] <- sum(pairwise_RMSSD_df[i], na.rm = T)
  
}

names(sum_vec) <- c("Visit 0 and 1, Stress Numeric",
                    "Visit 0 and 2, Stress Numeric",
                    "Visit 1 and 2, Stress Numeric",
                    "Visit 0 and 1, PSS",
                    "Visit 0 and 2, PSS",
                    "Visit 1 and 2, PSS",
                    "Visit 0 and 1, Postive Mood Score",
                    "Visit 0 and 2, Postive Mood Score",
                    "Visit 1 and 2, Postive Mood Score",
                    "Visit 0 and 1, Negative Mood Score",
                    "Visit 0 and 2, Negative Mood Score ",
                    "Visit 1 and 2, Negative Mood Score")

sum_vec_df <- as.data.frame(sum_vec)

colnames(sum_vec_df) <- c("RMSSD Difference")

kableExtra::kable(sum_vec_df)

```

```{r plot saving}

# Correlation plots
ggsave("vis0_vis1plot.png", plot = vis0_vis1plot)
ggsave("vis0_vis2plot.png", plot = vis0_vis2plot)
ggsave("vis1_vis2plot.png", plot = vis1_vis2plot)
ggsave("vis0_vis1hist.png", plot = vis0_vis1hist)
ggsave("RMSSD_line_plot.png", plot = RMSSD_line_plot, width = 10, height = 10)

```

```{r kable glimpses}

glimpse_EMA <- glimpse(EMA_num)

glimpse(stress_df[c(1:8)])


plot(lm_negative_vis2_bf)
```

```{r linear model data frame}

# Puts RMSSD values for each trimester into stress_df, subsets, mutates
lm_df <- inner_join(stress_df,
                    visit_RMSSD_df,
                     by = c("Idmaternal")) %>%
         subset(Idmaternal != 1229, select = c(1, 3, 4:6, 8, 9,
                                                13, 15, 25, 39:62)) %>%
          mutate(Birthweight_percentile_Oken = as.numeric(Birthweight_percentile_Oken)) %>%
          mutate(t0_parity = as.numeric(t0_parity)) %>%
          mutate(m1_info_gender = as.factor(m1_info_gender)) %>%
          mutate(m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg = as.numeric(m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg)) %>%
          mutate(ethnicity_mom = as.factor(ethnicity_mom)) %>%
          mutate(OBrisk_cat = as.factor(OBrisk_cat)) %>%
          mutate(telomere_TS_infant_Residual = as.numeric(telomere_TS_infant_Residual)) %>%
          mutate(t0_parity = ifelse(t0_parity >= 1, 1, 0)) %>%
          mutate(t0_parity = as.factor(t0_parity)) %>%
          drop_na(m1_info_gender) %>%
          mutate(m1_info_gender = droplevels(m1_info_gender))

```

```{r linear model birthweight}

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_stress_num_vis1_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                            data = lm_df[-c(6, 9, 10, 12, 13, 15:34)],
                            na.action = na.exclude)

summary(lm_stress_num_vis1_bw)

# Formula for stress numeric second visit linear model
lm_stress_num_vis2_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                            data = lm_df[-c(6, 9, 10, 11, 13, 14, 16:34)],
                            na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_stress_num_vis3_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                            data = lm_df[-c(6, 9, 10, 11, 12, 14, 15, 17:34)],
                            na.action = na.exclude)

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_pss_vis1_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                     data = lm_df[-c(6, 9:16, 18, 19, 21:34)],
                     na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_pss_vis2_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                     data = lm_df[-c(6, 9:17, 19, 20, 22:34)],
                     na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_pss_vis3_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                     data = lm_df[-c(6, 9:18, 20, 21, 23:34)],
                     na.action = na.exclude)

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_positive_vis1_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                          data = lm_df[-c(6, 9:22, 24, 25, 27:34)],
                          na.action = na.exclude)

summary(lm_positive_vis1_bw)

# Formula for stress numeric second visit linear model
lm_positive_vis2_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                          data = lm_df[-c(6, 9:23, 25, 26, 28:34)],
                          na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_positive_vis3_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                          data = lm_df[-c(6, 9:24, 26, 27, 29:34)],
                          na.action = na.exclude)

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_negative_vis1_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                          data = lm_df[-c(6, 9:28, 30, 31, 33:34)],
                          na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_negative_vis2_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                          data = lm_df[-c(6, 9:29, 31, 32, 34)],
                          na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_negative_vis3_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                          data = lm_df[-c(6, 9:30, 32, 33)],
                          na.action = na.exclude)

```

```{r robust variance data frames bf}

# Na omitted df for pss columns
no_na_stress_num_vis1_bf <- lm_df[-c(6, 8, 10, 12, 13, 15:34)] %>%
                              na.omit() %>%
                              mutate(m1_info_gender = droplevels(m1_info_gender))

no_na_stress_num_vis2_bf <- lm_df[-c(6, 8, 10, 11, 13, 14, 16:34)] %>%
                              na.omit() %>%
                              mutate(m1_info_gender = droplevels(m1_info_gender))

no_na_stress_num_vis3_bf <- lm_df[-c(6, 8, 10, 11, 12, 14, 15, 17:34)] %>% 
                              na.omit() %>%
                              mutate(m1_info_gender = droplevels(m1_info_gender))

# Na omitted df for stress numeric columns
no_na_pss_vis1_bf <- lm_df[-c(6, 8, 10:16, 18, 19, 21:34)] %>%
                              na.omit() %>%
                              mutate(m1_info_gender = droplevels(m1_info_gender))

no_na_pss_vis2_bf <- lm_df[-c(6, 8, 10:17, 19, 20, 22:34)] %>% 
                              na.omit() %>%
                              mutate(m1_info_gender = droplevels(m1_info_gender))

no_na_pss_vis3_bf <- lm_df[-c(6, 8, 10:18, 20, 21, 23:34)] %>% 
                              na.omit() %>%
                              mutate(m1_info_gender = droplevels(m1_info_gender))

# Na omitted df for positive mood score columns
no_na_positive_vis1_bf <- lm_df[-c(6, 8, 10:22, 24, 25, 27:34)] %>%
                              na.omit() %>%
                              mutate(m1_info_gender = droplevels(m1_info_gender))

no_na_positive_vis2_bf <- lm_df[-c(6, 8, 10:23, 25, 26, 28:34)] %>% 
                              na.omit() %>%
                              mutate(m1_info_gender = droplevels(m1_info_gender))

no_na_positive_vis3_bf <- lm_df[-c(6, 8, 10:24, 26, 27, 29:34)] %>% 
                              na.omit() %>%
                              mutate(m1_info_gender = droplevels(m1_info_gender))

# Na omitted df for negative mood score columns
no_na_negative_vis1_bf <- lm_df[-c(6, 8, 10:28, 30, 31, 33:34)] %>% 
                              na.omit() %>%
                              mutate(m1_info_gender = droplevels(m1_info_gender))

no_na_negative_vis2_bf <- lm_df[-c(6, 8, 10:29, 31, 32, 34)] %>% 
                              na.omit() %>%
                              mutate(m1_info_gender = droplevels(m1_info_gender))

no_na_negative_vis3_bf <- lm_df[-c(6, 8, 10:30, 32, 33)] %>% 
                              na.omit() %>%
                              mutate(m1_info_gender = droplevels(m1_info_gender))

```

```{r robust variance residuals and x}

# stress numeric visit 1 ------------------------------------------------------
lm_stress_num_vis1_bf_no_na <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                                  data = no_na_stress_num_vis1_bf)

resid_mat_stress_num_vis1 <- diag(resid(lm_stress_num_vis1_bf_no_na)^2)

x_mat_stress_num_vis1 <- model.matrix(~., data = no_na_stress_num_vis1_bf[-7])

rbe_stress_num_vis1 <- solve(t(x_mat_stress_num_vis1) %*% x_mat_stress_num_vis1) %*% (t(x_mat_stress_num_vis1) %*% resid_mat_stress_num_vis1 %*% (x_mat_stress_num_vis1)) %*% solve(t(x_mat_stress_num_vis1) %*% x_mat_stress_num_vis1)

stress_num_vis1_bf_se <- sqrt((rbe_stress_num_vis1[8,8]))

# stress numeric visit 2 ------------------------------------------------------
lm_stress_num_vis2_bf_no_na <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                                  data = no_na_stress_num_vis2_bf)

resid_mat_stress_num_vis2 <- diag(resid(lm_stress_num_vis2_bf_no_na)^2)

x_mat_stress_num_vis2 <- model.matrix(~., data = no_na_stress_num_vis2_bf[-7])

rbe_stress_num_vis2 <- solve(t(x_mat_stress_num_vis2) %*% x_mat_stress_num_vis2) %*% (t(x_mat_stress_num_vis2) %*% resid_mat_stress_num_vis2 %*% (x_mat_stress_num_vis2)) %*% solve(t(x_mat_stress_num_vis2) %*% x_mat_stress_num_vis2)

stress_num_vis2_bf_se <- sqrt(abs(rbe_stress_num_vis2[8,8]))

# stress numeric visit 3 ------------------------------------------------------
lm_stress_num_vis3_bf_no_na <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                                  data = no_na_stress_num_vis3_bf)

resid_mat_stress_num_vis3 <- diag(resid(lm_stress_num_vis3_bf_no_na)^2)

x_mat_stress_num_vis3 <- model.matrix(~., data = no_na_stress_num_vis3_bf[-7])

rbe_stress_num_vis3 <- solve(t(x_mat_stress_num_vis3) %*% x_mat_stress_num_vis3) %*% (t(x_mat_stress_num_vis3) %*% resid_mat_stress_num_vis3 %*% (x_mat_stress_num_vis3)) %*% solve(t(x_mat_stress_num_vis3) %*% x_mat_stress_num_vis3)

stress_num_vis3_bf_se <- sqrt(abs(rbe_stress_num_vis3[8,8]))

# PSS visit 1 ------------------------------------------------------
lm_pss_vis1_bf_no_na <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                                  data = no_na_pss_vis1_bf)

resid_mat_pss_vis1 <- diag(resid(lm_pss_vis1_bf_no_na)^2)

x_mat_pss_vis1 <- model.matrix(~., data = no_na_pss_vis1_bf[-7])

rbe_pss_vis1 <- solve(t(x_mat_pss_vis1) %*% x_mat_pss_vis1) %*% (t(x_mat_pss_vis1) %*% resid_mat_pss_vis1 %*% (x_mat_pss_vis1)) %*% solve(t(x_mat_pss_vis1) %*% x_mat_pss_vis1)

pss_vis1_bf_se <- sqrt(abs(rbe_pss_vis1[8,8]))

# PSS visit 2 ------------------------------------------------------
lm_pss_vis2_bf_no_na <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                                  data = no_na_pss_vis2_bf)

resid_mat_pss_vis2 <- diag(resid(lm_pss_vis2_bf_no_na)^2)

x_mat_pss_vis2 <- model.matrix(~., data = no_na_pss_vis2_bf[-7])

rbe_pss_vis2 <- solve(t(x_mat_pss_vis2) %*% x_mat_pss_vis2) %*% (t(x_mat_pss_vis2) %*% resid_mat_pss_vis2 %*% (x_mat_pss_vis2)) %*% solve(t(x_mat_pss_vis2) %*% x_mat_pss_vis2)

pss_vis2_bf_se <- sqrt(abs(rbe_pss_vis2[8,8]))

# PSS visit 3 ------------------------------------------------------
lm_pss_vis3_bf_no_na <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                                  data = no_na_pss_vis3_bf)

resid_mat_pss_vis3 <- diag(resid(lm_pss_vis3_bf_no_na)^2)

x_mat_pss_vis3 <- model.matrix(~., data = no_na_pss_vis3_bf[-7])

rbe_pss_vis3 <- solve(t(x_mat_pss_vis3) %*% x_mat_pss_vis3) %*% (t(x_mat_pss_vis3) %*% resid_mat_pss_vis3 %*% (x_mat_pss_vis3)) %*% solve(t(x_mat_pss_vis3) %*% x_mat_pss_vis3)

pss_vis3_bf_se <- sqrt(abs(rbe_pss_vis3[8,8]))

# Positive mood score visit 1 ------------------------------------------------------
lm_positive_vis1_bf_no_na <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                                  data = no_na_positive_vis1_bf)

resid_mat_positive_vis1 <- diag(resid(lm_positive_vis1_bf_no_na)^2)

x_mat_positive_vis1 <- model.matrix(~., data = no_na_positive_vis1_bf[-7])

rbe_positive_vis1 <- solve(t(x_mat_positive_vis1) %*% x_mat_positive_vis1) %*% (t(x_mat_positive_vis1) %*% resid_mat_positive_vis1 %*% (x_mat_positive_vis1)) %*% solve(t(x_mat_positive_vis1) %*% x_mat_positive_vis1)

positive_vis1_bf_se <- sqrt(abs(rbe_positive_vis1[8,8]))

# Positive mood score visit 2 ------------------------------------------------------
lm_positive_vis2_bf_no_na <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                                  data = no_na_positive_vis2_bf)

resid_mat_positive_vis2 <- diag(resid(lm_positive_vis2_bf_no_na)^2)

x_mat_positive_vis2 <- model.matrix(~., data = no_na_positive_vis2_bf[-7])

rbe_positive_vis2 <- solve(t(x_mat_positive_vis2) %*% x_mat_positive_vis2) %*% (t(x_mat_positive_vis2) %*% resid_mat_positive_vis2 %*% (x_mat_positive_vis2)) %*% solve(t(x_mat_positive_vis2) %*% x_mat_positive_vis2)

positive_vis2_bf_se <- sqrt(abs(rbe_positive_vis2[8,8]))

# Positive mood score visit 3 ------------------------------------------------------
lm_positive_vis3_bf_no_na <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                                  data = no_na_positive_vis3_bf)

resid_mat_positive_vis3 <- diag(resid(lm_positive_vis3_bf_no_na)^2)

x_mat_positive_vis3 <- model.matrix(~., data = no_na_positive_vis3_bf[-7])

rbe_positive_vis3 <- solve(t(x_mat_positive_vis3) %*% x_mat_positive_vis3) %*% (t(x_mat_positive_vis3) %*% resid_mat_positive_vis3 %*% (x_mat_positive_vis3)) %*% solve(t(x_mat_positive_vis3) %*% x_mat_positive_vis3)

positive_vis3_bf_se <- sqrt(abs(rbe_positive_vis3[8,8]))

# Negative mood score visit 1 ------------------------------------------------------
lm_negative_vis1_bf_no_na <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                                  data = no_na_negative_vis1_bf)

resid_mat_negative_vis1 <- diag(resid(lm_negative_vis1_bf_no_na)^2)

x_mat_negative_vis1 <- model.matrix(~., data = no_na_negative_vis1_bf[-7])

rbe_negative_vis1 <- solve(t(x_mat_negative_vis1) %*% x_mat_negative_vis1) %*% (t(x_mat_negative_vis1) %*% resid_mat_negative_vis1 %*% (x_mat_negative_vis1)) %*% solve(t(x_mat_negative_vis1) %*% x_mat_negative_vis1)

negative_vis1_bf_se <- sqrt(abs(rbe_negative_vis1[8,8]))

# Negative mood score visit 2 ------------------------------------------------------
lm_negative_vis2_bf_no_na <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                                  data = no_na_negative_vis2_bf)

resid_mat_negative_vis2 <- diag(resid(lm_negative_vis2_bf_no_na)^2)

x_mat_negative_vis2 <- model.matrix(~., data = no_na_negative_vis2_bf[-7])

rbe_negative_vis2 <- solve(t(x_mat_negative_vis2) %*% x_mat_negative_vis2) %*% (t(x_mat_negative_vis2) %*% resid_mat_negative_vis2 %*% (x_mat_negative_vis2)) %*% solve(t(x_mat_negative_vis2) %*% x_mat_negative_vis2)

negative_vis2_bf_se <- sqrt(abs(rbe_negative_vis2[8,8]))

# Negative mood score visit 3 ------------------------------------------------------
lm_negative_vis3_bf_no_na <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                                  data = no_na_negative_vis3_bf)

resid_mat_negative_vis3 <- diag(resid(lm_negative_vis3_bf_no_na)^2)

x_mat_negative_vis3 <- model.matrix(~., data = no_na_negative_vis3_bf[-7])

rbe_negative_vis3 <- solve(t(x_mat_negative_vis3) %*% x_mat_negative_vis3) %*% (t(x_mat_negative_vis3) %*% resid_mat_negative_vis3 %*% (x_mat_negative_vis3)) %*% solve(t(x_mat_negative_vis3) %*% x_mat_negative_vis3)

negative_vis3_bf_se <- sqrt(abs(rbe_negative_vis3[8,8]))

# Puts all se in a vector -----------------------------------------------------------

se_vec <- c(stress_num_vis1_bf_se,
            stress_num_vis2_bf_se,
            stress_num_vis3_bf_se,
            pss_vis1_bf_se,
            pss_vis2_bf_se,
            pss_vis3_bf_se,
            positive_vis1_bf_se,
            positive_vis2_bf_se,
            positive_vis3_bf_se,
            negative_vis1_bf_se,
            negative_vis2_bf_se,
            negative_vis3_bf_se)

se_vec

```

```{r linear model bf percentage}

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_stress_num_vis1_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                            data = lm_df[-c(6, 8, 10, 12, 13, 15:34)],
                            na.action = na.exclude)

summary(lm_stress_num_vis1_bf)

confint(lm_stress_num_vis1_bf)[8,]

# Formula for stress numeric second visit linear model
lm_stress_num_vis2_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                            data = lm_df[-c(6, 8, 10, 11, 13, 14, 16:34)],
                            na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_stress_num_vis3_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                            data = lm_df[-c(6, 8, 10, 11, 12, 14, 15, 17:34)],
                            na.action = na.exclude)

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_pss_vis1_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                     data = lm_df[-c(6, 8, 10:16, 18, 19, 21:34)],
                     na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_pss_vis2_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                     data = lm_df[-c(6, 8, 10:17, 19, 20, 22:34)],
                     na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_pss_vis3_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                     data = lm_df[-c(6, 8, 10:18, 20, 21, 23:34)],
                     na.action = na.exclude)

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_positive_vis1_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                          data = lm_df[-c(6, 8, 10:22, 24, 25, 27:34)],
                          na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_positive_vis2_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                          data = lm_df[-c(6, 8, 10:23, 25, 26, 28:34)],
                          na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_positive_vis3_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                          data = lm_df[-c(6, 8, 10:24, 26, 27, 29:34)],
                          na.action = na.exclude)

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_negative_vis1_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                          data = lm_df[-c(6, 8, 10:28, 30, 31, 33:34)],
                          na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_negative_vis2_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                          data = lm_df[-c(6, 8, 10:29, 31, 32, 34)],
                          na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_negative_vis3_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                          data = lm_df[-c(6, 8, 10:30, 32, 33)],
                          na.action = na.exclude)

```

```{r linear model telomere length}

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_stress_num_vis1_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                            data = lm_df[-c(6, 8, 9, 12, 13, 15:34)],
                              na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_stress_num_vis2_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                            data = lm_df[-c(6, 8, 9, 11, 13, 14, 16:34)],
                              na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_stress_num_vis3_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                            data = lm_df[-c(6, 8, 9, 11, 12, 14, 15, 17:34)],
                              na.action = na.exclude)

summary(lm_stress_num_vis3_telo)

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_pss_vis1_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                     data = lm_df[-c(6, 8, 9, 11:16, 18, 19, 21:34)],
                       na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_pss_vis2_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                     data = lm_df[-c(6, 8, 9, 11:17, 19, 20, 22:34)],
                       na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_pss_vis3_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                     data = lm_df[-c(6, 8, 9, 11:18, 20, 21, 23:34)],
                       na.action = na.exclude)

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_positive_vis1_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                          data = lm_df[-c(6, 8, 9, 11:22, 24, 25, 27:34)],
                            na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_positive_vis2_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                          data = lm_df[-c(6, 8, 9, 11:23, 25, 26, 28:34)],
                            na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_positive_vis3_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                          data = lm_df[-c(6, 8, 9, 11:24, 26, 27, 29:34)],
                            na.action = na.exclude)

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_negative_vis1_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                          data = lm_df[-c(6, 8, 9, 11:28, 30, 31, 33:34)],
                            na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_negative_vis2_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                          data = lm_df[-c(6, 8, 9, 11:29, 31, 32, 34)],
                            na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_negative_vis3_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                          data = lm_df[-c(6, 8, 9, 11:30, 32, 33)],
                            na.action = na.exclude)

```

```{r fitted vs residuals}

# This is an example of how to get a fitted vs residual plot, just to check the constant variance assumption
plot(lm_stress_num_vis1_bw, which = 1)

```

```{r confidence intervals}

#------------------------------------------------------------------

visit_1_matr_stress_num <- matrix(nrow = 3, ncol = 2)

visit_1_matr_stress_num[1,] = confint(lm_stress_num_vis1_bw,
                           parm = "visit_RMSSD_stress_num_0")

visit_1_matr_stress_num[2,] = c(coef(lm_stress_num_vis1_bf)[8] - stress_num_vis1_bf_se * 1.96,
                                coef(lm_stress_num_vis1_bf)[8] + stress_num_vis1_bf_se * 1.96)

visit_1_matr_stress_num[3,] = confint(lm_stress_num_vis1_telo,
                           parm = "visit_RMSSD_stress_num_0")

visit_1_coef_stress_num <- c(coef(lm_stress_num_vis1_bw)[9],
                             coef(lm_stress_num_vis1_bf)[8],
                             coef(lm_stress_num_vis1_telo)[8])

visit_1_matr_stress_num

#------------------------------------------------------------------

visit_1_matr_pss <- matrix(nrow = 3, ncol = 2)

visit_1_matr_pss[1,] = confint(lm_pss_vis1_bw,
                           parm = "visit_RMSSD_pss_0")

visit_1_matr_pss[2,] = c(coef(lm_pss_vis1_bf)[8] - pss_vis1_bf_se * 1.96,
                         coef(lm_pss_vis1_bf)[8] + pss_vis1_bf_se * 1.96)

visit_1_matr_pss[3,] = confint(lm_pss_vis1_telo,
                           parm = "visit_RMSSD_pss_0")

visit_1_coef_pss <- c(coef(lm_pss_vis1_bw)[9],
                      coef(lm_pss_vis1_bf)[8],
                      coef(lm_pss_vis1_telo)[8])
visit_1_coef_pss

#------------------------------------------------------------------

visit_1_matr_pos <- matrix(nrow = 3, ncol = 2)

visit_1_matr_pos[1,] = confint(lm_positive_vis1_bw,
                           parm = "visit_RMSSD_positive_0")

visit_1_matr_pos[2,] = c(coef(lm_positive_vis1_bf)[8] - positive_vis1_bf_se * 1.96,
                         coef(lm_positive_vis1_bf)[8] + positive_vis1_bf_se * 1.96)

visit_1_matr_pos[3,] = confint(lm_positive_vis1_telo,
                           parm = "visit_RMSSD_positive_0")

visit_1_coef_postive <- c(coef(lm_positive_vis1_bw)[9],
                          coef(lm_positive_vis1_bf)[8],
                          coef(lm_positive_vis1_telo)[8])

visit_1_coef_postive

#------------------------------------------------------------------

visit_1_matr_neg <- matrix(nrow = 3, ncol = 2)

visit_1_matr_neg[1,] = confint(lm_negative_vis1_bw,
                           parm = "visit_RMSSD_negative_0")

visit_1_matr_neg[2,] = c(coef(lm_negative_vis1_bf)[8] - negative_vis1_bf_se * 1.96,
                         coef(lm_negative_vis1_bf)[8] + negative_vis1_bf_se * 1.96)

visit_1_matr_neg[3,] = confint(lm_negative_vis1_telo,
                           parm = "visit_RMSSD_negative_0")

visit_1_coef_negative <- c(coef(lm_negative_vis1_bw)[9],
                           coef(lm_negative_vis1_bf)[8],
                           coef(lm_negative_vis1_telo)[8])

visit_1_coef_negative

#------------------------------------------------------------------

coef_visit_1 <- c(visit_1_coef_stress_num,
                  visit_1_coef_pss,
                  visit_1_coef_postive,
                  visit_1_coef_negative)

visit_1_matrix <- cbind(coef_visit_1,
                        rbind(visit_1_matr_stress_num,
                              visit_1_matr_pss,
                              visit_1_matr_pos,
                              visit_1_matr_neg
                        ))

colnames(visit_1_matrix) <- c("Mean", "2.5%", "97.5%")

rownames(visit_1_matrix) <- c("Strs Num BW", 
                              "Strs Num BF%",
                              "Strs Num TL",
                              "PSS BW", 
                              "PSS BF %",
                              "PSS TL",
                              "Pos M BW", 
                              "Pos M BF %",
                              "Pos M TL",
                              "Neg M BW", 
                              "Neg M BF %",
                              "Neg M TL")

visit_1_matrix

#------------------------------------------------------------------

visit_2_matr_stress_num <- matrix(nrow = 3, ncol = 2)

visit_2_matr_stress_num[1,] = confint(lm_stress_num_vis2_bw,
                           parm = "visit_RMSSD_stress_num_1")

visit_2_matr_stress_num[2,] = c(coef(lm_stress_num_vis2_bf)[8] - stress_num_vis2_bf_se * 1.96,
                                coef(lm_stress_num_vis2_bf)[8] + stress_num_vis2_bf_se * 1.96)

visit_2_matr_stress_num[3,] = confint(lm_stress_num_vis2_telo,
                           parm = "visit_RMSSD_stress_num_1")

visit_2_coef_stress_num <- c(coef(lm_stress_num_vis2_bw)[9],
                             coef(lm_stress_num_vis2_bf)[8],
                             coef(lm_stress_num_vis2_telo)[8])

visit_2_coef_stress_num

#------------------------------------------------------------------

visit_2_matr_pss <- matrix(nrow = 3, ncol = 2)

visit_2_matr_pss[1,] = confint(lm_pss_vis2_bw,
                           parm = "visit_RMSSD_pss_1")

visit_2_matr_pss[2,] = c(coef(lm_pss_vis2_bf)[8] - pss_vis2_bf_se * 1.96,
                         coef(lm_pss_vis2_bf)[8] + pss_vis2_bf_se * 1.96)

visit_2_matr_pss[3,] = confint(lm_pss_vis2_telo,
                           parm = "visit_RMSSD_pss_1")

visit_2_coef_pss <- c(coef(lm_pss_vis2_bw)[9],
                      coef(lm_pss_vis2_bf)[8],
                      coef(lm_pss_vis2_telo)[8])

visit_2_coef_pss

#------------------------------------------------------------------

visit_2_matr_pos <- matrix(nrow = 3, ncol = 2)

visit_2_matr_pos[1,] = confint(lm_positive_vis2_bw,
                           parm = "visit_RMSSD_positive_1")

visit_2_matr_pos[2,] = c(coef(lm_positive_vis2_bf)[8] - positive_vis2_bf_se * 1.96,
                         coef(lm_positive_vis2_bf)[8] + positive_vis2_bf_se * 1.96)

visit_2_matr_pos[3,] = confint(lm_positive_vis2_telo,
                           parm = "visit_RMSSD_positive_1")

visit_2_coef_positive <- c(coef(lm_positive_vis2_bw)[9],
                          coef(lm_positive_vis2_bf)[8],
                          coef(lm_positive_vis2_telo)[8])

visit_2_coef_positive

#------------------------------------------------------------------

visit_2_matr_neg <- matrix(nrow = 3, ncol = 2)

visit_2_matr_neg[1,] = confint(lm_negative_vis2_bw,
                           parm = "visit_RMSSD_negative_1")

visit_2_matr_neg[2,] = c(coef(lm_negative_vis2_bf)[8] - negative_vis2_bf_se * 1.96,
                         coef(lm_negative_vis2_bf)[8] + negative_vis2_bf_se * 1.96)

visit_2_matr_neg[3,] = confint(lm_negative_vis2_telo,
                           parm = "visit_RMSSD_negative_1")

visit_2_coef_negative <- c(coef(lm_negative_vis2_bw)[9],
                           coef(lm_negative_vis2_bf)[8],
                           coef(lm_negative_vis2_telo)[8])

visit_2_coef_negative


#------------------------------------------------------------------

coef_visit_2 <- c(visit_2_coef_stress_num,
                  visit_2_coef_pss,
                  visit_2_coef_positive,
                  visit_2_coef_negative)

visit_2_matrix <- cbind(coef_visit_2,
                        rbind(visit_2_matr_stress_num,
                              visit_2_matr_pss,
                              visit_2_matr_pos,
                              visit_2_matr_neg
                        ))

colnames(visit_2_matrix) <- c("Mean", "2.5%", "97.5%")
rownames(visit_2_matrix) <- c("Strs Num BW", 
                              "Strs Num BF%",
                              "Strs Num TL",
                              "PSS BW", 
                              "PSS BF %",
                              "PSS TL",
                              "Pos M BW", 
                              "Pos M BF %",
                              "Pos M TL",
                              "Neg M BW", 
                              "Neg M BF %",
                              "Neg M TL")


visit_2_matrix

#------------------------------------------------------------------

visit_3_matr_stress_num <- matrix(nrow = 3, ncol = 2)

visit_3_matr_stress_num[1,] = confint(lm_stress_num_vis3_bw,
                           parm = "visit_RMSSD_stress_num_2")

visit_3_matr_stress_num[2,] = c(coef(lm_stress_num_vis3_bf)[8] - stress_num_vis3_bf_se * 1.96,
                                coef(lm_stress_num_vis3_bf)[8] + stress_num_vis3_bf_se * 1.96)

visit_3_matr_stress_num[3,] = confint(lm_stress_num_vis3_telo,
                           parm = "visit_RMSSD_stress_num_2")

visit_3_coef_stress_num <- c(coef(lm_stress_num_vis3_bw)[9],
                             coef(lm_stress_num_vis3_bf)[8],
                             coef(lm_stress_num_vis3_telo)[8])

visit_3_coef_stress_num

#------------------------------------------------------------------

visit_3_matr_pss <- matrix(nrow = 3, ncol = 2)

visit_3_matr_pss[1,] = confint(lm_pss_vis3_bw,
                           parm = "visit_RMSSD_pss_2")

visit_3_matr_pss[2,] = c(coef(lm_pss_vis3_bf)[8] - pss_vis3_bf_se * 1.96,
                         coef(lm_pss_vis3_bf)[8] + pss_vis3_bf_se * 1.96)

visit_3_matr_pss[3,] = confint(lm_pss_vis3_telo,
                           parm = "visit_RMSSD_pss_2")

visit_3_coef_pss <- c(coef(lm_pss_vis3_bw)[9],
                      coef(lm_pss_vis3_bf)[8],
                      coef(lm_pss_vis3_telo)[8])

visit_3_coef_pss

#------------------------------------------------------------------

visit_3_matr_pos <- matrix(nrow = 3, ncol = 2)

visit_3_matr_pos[1,] = confint(lm_positive_vis3_bw,
                           parm = "visit_RMSSD_positive_2")

visit_3_matr_pos[2,] = c(coef(lm_positive_vis3_bf)[8] - positive_vis3_bf_se * 1.96,
                         coef(lm_positive_vis3_bf)[8] + positive_vis3_bf_se * 1.96)

visit_3_matr_pos[3,] = confint(lm_positive_vis3_telo,
                           parm = "visit_RMSSD_positive_2")

visit_3_coef_positive <- c(coef(lm_positive_vis3_bw)[9],
                           coef(lm_positive_vis3_bf)[8],
                           coef(lm_positive_vis3_telo)[8])

visit_3_coef_positive

#------------------------------------------------------------------

visit_3_matr_neg <- matrix(nrow = 3, ncol = 2)

visit_3_matr_neg[1,] = confint(lm_negative_vis3_bw,
                           parm = "visit_RMSSD_negative_2")

visit_3_matr_neg[2,] = c(coef(lm_negative_vis3_bf)[8] - negative_vis3_bf_se * 1.96,
                         coef(lm_positive_vis3_bw)[8] + negative_vis3_bf_se * 1.96)

visit_3_matr_neg[3,] = confint(lm_negative_vis3_telo,
                           parm = "visit_RMSSD_negative_2")

visit_3_coef_negative <- c(coef(lm_negative_vis3_bw)[9],
                           coef(lm_negative_vis3_bf)[8],
                           coef(lm_negative_vis3_telo)[8])

visit_3_coef_negative

#------------------------------------------------------------------

coef_visit_3 <- c(visit_3_coef_stress_num,
                  visit_3_coef_pss,
                  visit_3_coef_positive,
                  visit_3_coef_negative)

visit_3_matrix <- cbind(coef_visit_3,
                        rbind(visit_3_matr_stress_num,
                              visit_3_matr_pss,
                              visit_3_matr_pos,
                              visit_3_matr_neg
                        ))

colnames(visit_3_matrix) <- c("Mean", "2.5%", "97.5%")
rownames(visit_3_matrix) <- c("Strs Num BW", 
                              "Strs Num BF%",
                              "Strs Num TL",
                              "PSS BW", 
                              "PSS BF %",
                              "PSS TL",
                              "Pos M BW", 
                              "Pos M BF %",
                              "Pos M TL",
                              "Neg M BW", 
                              "Neg M BF %",
                              "Neg M TL")


visit_3_matrix

#------------------------------------------------------------------

# Table of confidence intervals for 3 visits, 3 outcomes, 4 stress measures
# We want to see CI which do not include 0
as.data.frame(cbind(visit_1_matrix,
                    visit_2_matrix,
                    visit_3_matrix))

#------------------------------------------------------------------

```

```{r variance data frames}

# another way of calculating RMSSD by ID, Trimester, and Day --------------
rslt_var <- EMA_num %>%
  group_by(Idmaternal, Trimester, Day) %>%
  summarise(
    var_stress_num = var(StressedNumeric[!is.na(StressedNumeric)]),
    mean_stress_num = mean(StressedNumeric),
    var_pss = var(PercievedStressScore[!is.na(PercievedStressScore)]),
    mean_pss = mean(PercievedStressScore),
    var_positive = var(PositiveMoodScore[!is.na(PositiveMoodScore)]),
    mean_postive = mean(PositiveMoodScore),
    var_negative = var(NegativeMoodScore[!is.na(NegativeMoodScore)]),
    mean_negative = mean(NegativeMoodScore)
  )

# Group day RMSSD by ID and visit to give visit RMSSD for each id
visit_var_df <- rslt_var %>% 
                  group_by(Idmaternal, Trimester) %>% 
                  summarise(visit_var_stress_num = mean(var_stress_num),
                            mean_stressNum = mean(mean_stress_num),
                            visit_var_pss = mean(var_pss),
                            meanPss = mean(mean_pss),
                            visit_var_positive = mean(var_positive),
                            meanPositive = mean(mean_postive),
                            visit_var_negative = mean(var_negative),
                            meanNegative = mean(mean_negative)) %>%
                  mutate(Trimester = as.factor(Trimester)) %>%
                  pivot_wider(names_from = Trimester,
                              values_from = c(visit_var_stress_num,
                                              mean_stressNum,
                                              visit_var_pss,
                                              meanPss,
                                              visit_var_positive,
                                              meanPositive,
                                              visit_var_negative,
                                              meanNegative))

# Puts RMSSD values for each trimester into stress_df, subsets, mutates
lm_df_var <- inner_join(stress_df,
                        visit_var_df,
                        by = c("Idmaternal")) %>%
          subset(Idmaternal != 1229, select = c(1, 3, 4:6, 8, 9,
                                                13, 15, 25, 39:62)) %>%
          mutate(Birthweight_percentile_Oken = as.numeric(Birthweight_percentile_Oken)) %>%
          mutate(t0_parity = as.numeric(t0_parity)) %>%
          mutate(m1_info_gender = as.factor(m1_info_gender)) %>%
          mutate(m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg = as.numeric(m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg)) %>%
          mutate(ethnicity_mom = as.factor(ethnicity_mom)) %>%
          mutate(OBrisk_cat = as.factor(OBrisk_cat)) %>%
          mutate(telomere_TS_infant_Residual = as.numeric(telomere_TS_infant_Residual)) %>%
          mutate(t0_parity = ifelse(t0_parity >= 1, 1, 0)) %>%
          mutate(t0_parity = as.factor(t0_parity))

```

```{r variance linear model birthweight}

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_var_stress_num_vis1_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                                data = lm_df_var[-c(6, 9, 10, 12, 13, 15:34)],
                                na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_var_stress_num_vis2_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                            data = lm_df_var[-c(6, 9, 10, 11, 13, 14, 16:34)],
                            na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_var_stress_num_vis3_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                                data = lm_df_var[-c(6, 9, 10, 11,
                                                    12, 14, 15, 17:34)],
                                na.action = na.exclude)

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_var_pss_vis1_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                     data = lm_df_var[-c(6, 9:16, 18, 19, 21:34)],
                     na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_var_pss_vis2_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                     data = lm_df_var[-c(6, 9:17, 19, 20, 22:34)],
                     na.action = na.exclude)

summary(lm_var_pss_vis2_bw)

# Formula for stress numeric third visit linear model
lm_var_pss_vis3_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                     data = lm_df_var[-c(6, 9:18, 20, 21, 23:34)],
                     na.action = na.exclude)

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_var_positive_vis1_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                          data = lm_df_var[-c(6, 9:22, 24, 25, 27:34)],
                          na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_var_positive_vis2_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                          data = lm_df_var[-c(6, 9:23, 25, 26, 28:34)],
                          na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_var_positive_vis3_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                          data = lm_df_var[-c(6, 9:24, 26, 27, 29:34)],
                          na.action = na.exclude)

summary(lm_negative_vis3_bw)
summary(lm_var_negative_vis3_bw)

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_var_negative_vis1_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                          data = lm_df_var[-c(6, 9:28, 30, 31, 33:34)],
                          na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_var_negative_vis2_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                          data = lm_df_var[-c(6, 9:29, 31, 32, 34)],
                          na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_var_negative_vis3_bw <- lm(formula = Birthweight_percentile_Oken ~ .,
                          data = lm_df_var[-c(6, 9:30, 32, 33)],
                          na.action = na.exclude)


```


```{r variance linear model bf percentage}

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_var_stress_num_vis1_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                            data = lm_df_var[-c(6, 8, 10, 12, 13, 15:34)],
                            na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_var_stress_num_vis2_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                            data = lm_df_var[-c(6, 8, 10, 11, 13, 14, 16:34)],
                            na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_var_stress_num_vis3_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                            data = lm_df_var[-c(6, 8, 10, 11, 12, 14, 15, 17:34)],
                            na.action = na.exclude)

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_var_pss_vis1_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                     data = lm_df_var[-c(6, 8, 10:16, 18, 19, 21:34)],
                     na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_var_pss_vis2_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                     data = lm_df_var[-c(6, 8, 10:17, 19, 20, 22:34)],
                     na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_var_pss_vis3_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                     data = lm_df_var[-c(6, 8, 10:18, 20, 21, 23:34)],
                     na.action = na.exclude)

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_var_positive_vis1_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                          data = lm_df_var[-c(6, 8, 10:22, 24, 25, 27:34)],
                          na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_var_positive_vis2_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                          data = lm_df_var[-c(6, 8, 10:23, 25, 26, 28:34)],
                          na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_var_positive_vis3_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                          data = lm_df_var[-c(6, 8, 10:24, 26, 27, 29:34)],
                          na.action = na.exclude)

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_var_negative_vis1_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                          data = lm_df_var[-c(6, 8, 10:28, 30, 31, 33:34)],
                          na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_var_negative_vis2_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                          data = lm_df_var[-c(6, 8, 10:29, 31, 32, 34)],
                          na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_var_negative_vis3_bf <- lm(formula = m1_dxapfat_sa_ga_corrected_sfreplaced_m1avg ~ .,
                          data = lm_df_var[-c(6, 8, 10:30, 32, 33)],
                          na.action = na.exclude)

```

```{r variance linear model telomere length}

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_var_stress_num_vis1_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                            data = lm_df_var[-c(6, 8, 9, 12, 13, 15:34)],
                              na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_var_stress_num_vis2_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                            data = lm_df_var[-c(6, 8, 9, 11, 13, 14, 16:34)],
                              na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_var_stress_num_vis3_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                            data = lm_df_var[-c(6, 8, 9, 11, 12, 14, 15, 17:34)],
                              na.action = na.exclude)

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_var_pss_vis1_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                     data = lm_df_var[-c(6, 8, 9, 11:16, 18, 19, 21:34)],
                       na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_var_pss_vis2_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                     data = lm_df_var[-c(6, 8, 9, 11:17, 19, 20, 22:34)],
                       na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_var_pss_vis3_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                     data = lm_df_var[-c(6, 8, 9, 11:18, 20, 21, 23:34)],
                       na.action = na.exclude)

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_var_positive_vis1_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                          data = lm_df_var[-c(6, 8, 9, 11:22, 24, 25, 27:34)],
                            na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_var_positive_vis2_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                          data = lm_df_var[-c(6, 8, 9, 11:23, 25, 26, 28:34)],
                            na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_var_positive_vis3_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                          data = lm_df_var[-c(6, 8, 9, 11:24, 26, 27, 29:34)],
                            na.action = na.exclude)

#--------------------------------------------------------------------
# Formula for stress numeric first visit linear model
lm_var_negative_vis1_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                          data = lm_df_var[-c(6, 8, 9, 11:28, 30, 31, 33:34)],
                            na.action = na.exclude)

# Formula for stress numeric second visit linear model
lm_var_negative_vis2_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                          data = lm_df_var[-c(6, 8, 9, 11:29, 31, 32, 34)],
                            na.action = na.exclude)

# Formula for stress numeric third visit linear model
lm_var_negative_vis3_telo <- lm(formula = telomere_TS_infant_Residual ~ .,
                          data = lm_df_var[-c(6, 8, 9, 11:30, 32, 33)],
                            na.action = na.exclude)

```

```{r variance confidence intervals}

#------------------------------------------------------------------

visit_1_matr_stress_num_var <- matrix(nrow = 3, ncol = 2)

visit_1_matr_stress_num_var[1,] = confint(lm_var_stress_num_vis1_bw,
                           parm = "visit_var_stress_num_0")

visit_1_matr_stress_num_var[2,] = confint(lm_var_stress_num_vis1_bf,
                           parm = "visit_var_stress_num_0")

visit_1_matr_stress_num_var[3,] = confint(lm_var_stress_num_vis1_telo,
                           parm = "visit_var_stress_num_0")

visit_1_coef_stress_num_var <- c(coef(lm_var_stress_num_vis1_bw)[9],
                             coef(lm_var_stress_num_vis1_bf)[8],
                             coef(lm_var_stress_num_vis1_telo)[8])

#------------------------------------------------------------------

visit_1_matr_pss_var <- matrix(nrow = 3, ncol = 2)

visit_1_matr_pss_var[1,] = confint(lm_var_pss_vis1_bw,
                           parm = "visit_var_pss_0")

visit_1_matr_pss_var[2,] = confint(lm_var_pss_vis1_bf,
                           parm = "visit_var_pss_0")

visit_1_matr_pss_var[3,] = confint(lm_var_pss_vis1_telo,
                           parm = "visit_var_pss_0")

visit_1_coef_pss_var <- c(coef(lm_var_pss_vis1_bw)[9],
                      coef(lm_var_pss_vis1_bf)[8],
                      coef(lm_var_pss_vis1_telo)[8])
visit_1_coef_pss_var

#------------------------------------------------------------------

visit_1_matr_pos_var <- matrix(nrow = 3, ncol = 2)

visit_1_matr_pos_var[1,] = confint(lm_var_positive_vis1_bw,
                           parm = "visit_var_positive_0")

visit_1_matr_pos_var[2,] = confint(lm_var_positive_vis1_bf,
                           parm = "visit_var_positive_0")

visit_1_matr_pos_var[3,] = confint(lm_var_positive_vis1_telo,
                           parm = "visit_var_positive_0")

visit_1_coef_postive_var <- c(coef(lm_var_positive_vis1_bw)[9],
                          coef(lm_var_positive_vis1_bf)[8],
                          coef(lm_var_positive_vis1_telo)[8])

visit_1_coef_postive_var

#------------------------------------------------------------------

visit_1_matr_neg_var <- matrix(nrow = 3, ncol = 2)

visit_1_matr_neg_var[1,] = confint(lm_var_negative_vis1_bw,
                           parm = "visit_var_negative_0")

visit_1_matr_neg_var[2,] = confint(lm_var_negative_vis1_bf,
                           parm = "visit_var_negative_0")

visit_1_matr_neg_var[3,] = confint(lm_var_negative_vis1_telo,
                           parm = "visit_var_negative_0")

visit_1_coef_negative_var <- c(coef(lm_var_negative_vis1_bw)[9],
                           coef(lm_var_negative_vis1_bf)[8],
                           coef(lm_var_negative_vis1_telo)[8])

visit_1_coef_negative_var

#------------------------------------------------------------------

coef_visit_1_var <- c(visit_1_coef_stress_num,
                  visit_1_coef_pss,
                  visit_1_coef_postive,
                  visit_1_coef_negative)

visit_1_matrix_var <- cbind(coef_visit_1_var,
                        rbind(visit_1_matr_stress_num_var,
                              visit_1_matr_pss_var,
                              visit_1_matr_pos_var,
                              visit_1_matr_neg_var
                        ))

colnames(visit_1_matrix_var) <- c("Mean", "2.5%", "97.5%")

rownames(visit_1_matrix_var) <-  c("Strs Num BW", 
                              "Strs Num BF%",
                              "Strs Num TL",
                              "PSS BW", 
                              "PSS BF %",
                              "PSS TL",
                              "Pos M BW", 
                              "Pos M BF %",
                              "Pos M TL",
                              "Neg M BW", 
                              "Neg M BF %",
                              "Neg M TL")

visit_1_matrix_var

#------------------------------------------------------------------

visit_2_matr_stress_num_var <- matrix(nrow = 3, ncol = 2)

visit_2_matr_stress_num_var[1,] = confint(lm_var_stress_num_vis2_bw,
                           parm = "visit_var_stress_num_1")

visit_2_matr_stress_num_var[2,] = confint(lm_var_stress_num_vis2_bf,
                           parm = "visit_var_stress_num_1")

visit_2_matr_stress_num_var[3,] = confint(lm_var_stress_num_vis2_telo,
                           parm = "visit_var_stress_num_1")

visit_2_coef_stress_num_var <- c(coef(lm_var_stress_num_vis2_bw)[9],
                             coef(lm_var_stress_num_vis2_bf)[8],
                             coef(lm_var_stress_num_vis2_telo)[8])

visit_2_coef_stress_num_var

#------------------------------------------------------------------

visit_2_matr_pss_var <- matrix(nrow = 3, ncol = 2)

visit_2_matr_pss_var[1,] = confint(lm_var_pss_vis2_bw,
                           parm = "visit_var_pss_1")

visit_2_matr_pss_var[2,] = confint(lm_var_pss_vis2_bf,
                           parm = "visit_var_pss_1")

visit_2_matr_pss_var[3,] = confint(lm_var_pss_vis2_telo,
                           parm = "visit_var_pss_1")

visit_2_coef_pss_var <- c(coef(lm_var_pss_vis2_bw)[9],
                      coef(lm_var_pss_vis2_bf)[8],
                      coef(lm_var_pss_vis2_telo)[8])

visit_2_coef_pss_var

#------------------------------------------------------------------

visit_2_matr_pos_var <- matrix(nrow = 3, ncol = 2)

visit_2_matr_pos_var[1,] = confint(lm_var_positive_vis2_bw,
                           parm = "visit_var_positive_1")

visit_2_matr_pos_var[2,] = confint(lm_var_positive_vis2_bf,
                           parm = "visit_var_positive_1")

visit_2_matr_pos_var[3,] = confint(lm_var_positive_vis2_telo,
                           parm = "visit_var_positive_1")

visit_2_coef_positive_var <- c(coef(lm_var_positive_vis2_bw)[9],
                          coef(lm_var_positive_vis2_bf)[8],
                          coef(lm_var_positive_vis2_telo)[8])

visit_2_coef_positive_var

#------------------------------------------------------------------

visit_2_matr_neg_var <- matrix(nrow = 3, ncol = 2)

visit_2_matr_neg_var[1,] = confint(lm_var_negative_vis2_bw,
                           parm = "visit_var_negative_1")

visit_2_matr_neg_var[2,] = confint(lm_var_negative_vis2_bf,
                           parm = "visit_var_negative_1")

visit_2_matr_neg_var[3,] = confint(lm_var_negative_vis2_telo,
                           parm = "visit_var_negative_1")

visit_2_coef_negative_var <- c(coef(lm_var_negative_vis2_bw)[9],
                           coef(lm_var_negative_vis2_bf)[8],
                           coef(lm_var_negative_vis2_telo)[8])

visit_2_coef_negative_var


#------------------------------------------------------------------

coef_visit_2_var <- c(visit_2_coef_stress_num_var,
                  visit_2_coef_pss_var,
                  visit_2_coef_positive_var,
                  visit_2_coef_negative_var)

visit_2_matrix_var <- cbind(coef_visit_2_var,
                        rbind(visit_2_matr_stress_num_var,
                              visit_2_matr_pss_var,
                              visit_2_matr_pos_var,
                              visit_2_matr_neg_var
                        ))

colnames(visit_2_matrix_var) <- c("Mean", "2.5%", "97.5%")

rownames(visit_2_matrix_var) <-  c("Strs Num BW", 
                              "Strs Num BF%",
                              "Strs Num TL",
                              "PSS BW", 
                              "PSS BF %",
                              "PSS TL",
                              "Pos M BW", 
                              "Pos M BF %",
                              "Pos M TL",
                              "Neg M BW", 
                              "Neg M BF %",
                              "Neg M TL")
visit_2_matrix_var

#------------------------------------------------------------------

visit_3_matr_stress_num_var <- matrix(nrow = 3, ncol = 2)

visit_3_matr_stress_num_var[1,] = confint(lm_var_stress_num_vis3_bw,
                           parm = "visit_var_stress_num_2")

visit_3_matr_stress_num_var[2,] = confint(lm_var_stress_num_vis3_bf,
                           parm = "visit_var_stress_num_2")

visit_3_matr_stress_num_var[3,] = confint(lm_var_stress_num_vis3_telo,
                           parm = "visit_var_stress_num_2")

visit_3_coef_stress_num_var <- c(coef(lm_var_stress_num_vis3_bw)[9],
                             coef(lm_var_stress_num_vis3_bf)[8],
                             coef(lm_var_stress_num_vis3_telo)[8])

visit_3_coef_stress_num_var

#------------------------------------------------------------------

visit_3_matr_pss_var <- matrix(nrow = 3, ncol = 2)

visit_3_matr_pss_var[1,] = confint(lm_var_pss_vis3_bw,
                           parm = "visit_var_pss_2")

visit_3_matr_pss_var[2,] = confint(lm_var_pss_vis3_bf,
                           parm = "visit_var_pss_2")

visit_3_matr_pss_var[3,] = confint(lm_var_pss_vis3_telo,
                           parm = "visit_var_pss_2")

visit_3_coef_pss_var <- c(coef(lm_var_pss_vis3_bw)[9],
                      coef(lm_var_pss_vis3_bf)[8],
                      coef(lm_var_pss_vis3_telo)[8])

visit_3_coef_pss_var

summary(lm_var_positive_vis3_bw)

#------------------------------------------------------------------

visit_3_matr_pos_var <- matrix(nrow = 3, ncol = 2)

visit_3_matr_pos_var[1,] = confint(lm_var_positive_vis3_bw,
                           parm = "visit_var_positive_2")

visit_3_matr_pos_var[2,] = confint(lm_var_positive_vis3_bf,
                           parm = "visit_var_positive_2")

visit_3_matr_pos_var[3,] = confint(lm_var_positive_vis3_telo,
                           parm = "visit_var_positive_2")

visit_3_coef_positive_var <- c(coef(lm_var_positive_vis3_bw)[9],
                          coef(lm_var_positive_vis3_bf)[8],
                          coef(lm_var_positive_vis3_telo)[8])

visit_3_coef_positive_var

#------------------------------------------------------------------

visit_3_matr_neg_var <- matrix(nrow = 3, ncol = 2)

visit_3_matr_neg_var[1,] = confint(lm_var_negative_vis3_bw,
                           parm = "visit_var_negative_2")

visit_3_matr_neg_var[2,] = confint(lm_var_negative_vis3_bf,
                           parm = "visit_var_negative_2")

visit_3_matr_neg_var[3,] = confint(lm_var_negative_vis3_telo,
                           parm = "visit_var_negative_2")

visit_3_coef_negative_var <- c(coef(lm_var_negative_vis3_bw)[9],
                           coef(lm_var_negative_vis3_bf)[8],
                           coef(lm_var_negative_vis3_telo)[8])

visit_3_coef_negative_var


#------------------------------------------------------------------

coef_visit_3_var <- c(visit_3_coef_stress_num_var,
                  visit_3_coef_pss_var,
                  visit_3_coef_positive_var,
                  visit_3_coef_negative_var)

visit_3_matrix_var <- cbind(coef_visit_3_var,
                        rbind(visit_3_matr_stress_num_var,
                              visit_3_matr_pss_var,
                              visit_3_matr_pos_var,
                              visit_3_matr_neg_var
                        ))

colnames(visit_3_matrix_var) <- c("Mean", "2.5%", "97.5%")

rownames(visit_3_matrix_var) <-  c("Strs Num BW", 
                              "Strs Num BF%",
                              "Strs Num TL",
                              "PSS BW", 
                              "PSS BF %",
                              "PSS TL",
                              "Pos M BW", 
                              "Pos M BF %",
                              "Pos M TL",
                              "Neg M BW", 
                              "Neg M BF %",
                              "Neg M TL")

visit_3_matrix_var

#------------------------------------------------------------------

# Table of confidence intervals for 3 visits, 3 outcomes, 4 stress measures
# We want to see CI which do not include 0
as.data.frame(cbind(visit_1_matrix_var,
                    visit_2_matrix_var,
                    visit_3_matrix_var))

#------------------------------------------------------------------

```


```{r}

#varience 
#we want to see the outo corealtion if it doesn't move so it is just varianve

visit_1_matrix_var <- round(visit_1_matrix_var , digits = 2) 
visit_2_matrix_var <- round(visit_2_matrix_var , digits = 2) 
visit_3_matrix_var <- round(visit_3_matrix_var , digits = 2) 

```

```{r}
table_text <- cbind(c("Stress Type",row.names(visit_1_matrix_var)),
                   c("Mean",visit_1_matrix_var[,1]),
                   c("CI Lower",visit_1_matrix_var[,2] ),
                   c("CI Upper", visit_1_matrix_var[,3])) %>% 
  unname()

forest_V1_var <- forestplot(
  labeltext = (table_text),
  mean = c(NA, visit_1_matrix_var[,1]),
  lower = c(NA, visit_1_matrix_var[,2]),
  upper = c(NA, visit_1_matrix_var[,3]),
  graph.pos = "left",
  boxsize = c(0.3),
  title = "Visit 1",
  align = c("l", "c", "c", "c"),
  graphwidth = unit(10, "cm"),
  col=fpColors(box="royalblue",
               line = "black", 
               summary = "royalblue",
               hrz_lines = "#444444"),
  txt_gp = fpTxtGp(xlab = gpar(cex = 1),
                   ticks = gpar(cex = 0.75),
                   title = gpar(cex = 0.75),
                   label = gpar(cex = 0.75),
                   summary = gpar(cex = 0.75)),
  hrzl_lines = list("2" = gpar(lty = 2)),
  shapes_gp = fpShapesGp(lines = gpar(lwd = 2)),
  is.summary = c(TRUE,rep(FALSE,12)), #makes the title bold
  xlab = "Variance"
  )
forest_V1_var
```


```{r}
table_text2 <- cbind(c("Stress Type",row.names(visit_2_matrix_var)),
                   c("Mean",visit_2_matrix_var[,1]),
                   c("CI Lower",visit_2_matrix_var[,2] ),
                   c("CI Upper", visit_2_matrix_var[,3])) %>% 
  unname()

#forest plot for visit 1 using Variance instead of RMSSD to see if there is a outocorelation between them 
forest_V2_var <- forestplot(
  labeltext = (table_text),
  mean = c(NA, visit_2_matrix_var[,1]),
  lower = c(NA, visit_2_matrix_var[,2]),
  upper = c(NA, visit_2_matrix_var[,3]),
  graph.pos = "left",
  boxsize = c(0.3),
  title = "Visit 2",
  align = c("l", "c", "c", "c"),
  graphwidth = unit(10, "cm"),
  col=fpColors(box="royalblue",
               line = "black", 
               summary = "royalblue",
               hrz_lines = "#444444"),
  txt_gp = fpTxtGp(xlab = gpar(cex = 1),
                   ticks = gpar(cex = 0.75),
                   title = gpar(cex = 0.75),
                   label = gpar(cex = 0.75),
                   summary = gpar(cex = 0.75)),
  hrzl_lines = list("2" = gpar(lty = 2)),
  shapes_gp = fpShapesGp(lines = gpar(lwd = 2)),
  is.summary = c(TRUE,rep(FALSE,12)), #makes the title bold
  xlab = "Variance"
  )
forest_V2_var
```

```{r}
#pick the column for names/mean/ lower and upper confidence interval
table_text3 <- cbind(c("Stress Type",row.names(visit_3_matrix_var)),
                   c("Mean",visit_3_matrix_var[,1]),
                   c("CI Lower",visit_3_matrix_var[,2] ),
                   c("CI Upper", visit_3_matrix_var[,3])) %>% 
  unname()

#forest plot for visit 3 using Variance instead of RMSSD to see if there is a outocorelation between them 
forest_V3_var <- forestplot(
  labeltext = (table_text3),
  mean = c(NA, visit_3_matrix_var[,1]),
  lower = c(NA, visit_3_matrix_var[,2]),
  upper = c(NA, visit_3_matrix_var[,3]),
  graph.pos = "left",
  boxsize = c(0.3),
  title = "Visit 3",
  align = c("l", "c", "c", "c"),
  graphwidth = unit(10, "cm"),
  col=fpColors(box="royalblue",
               line = "black", 
               summary = "royalblue",
               hrz_lines = "#444444"),
  txt_gp = fpTxtGp(xlab = gpar(cex = 1),
                   ticks = gpar(cex = 0.75),
                   title = gpar(cex = 0.75),
                   label = gpar(cex = 0.75),
                   summary = gpar(cex = 0.75)),
  hrzl_lines = list("2" = gpar(lty = 2)),
  shapes_gp = fpShapesGp(lines = gpar(lwd = 2)),
  is.summary = c(TRUE,rep(FALSE,12)), #makes the title bold
  xlab = "Variance"
  )
forest_V3_var
```
```{r save the plot}

png('forest_V1_var.png', res = 300, width = 7.5, height = 7.5, units = "in")
forest_V1_var
dev.off()


png('forest_V2_var.png', res = 300, width = 7.5, height = 7.5, units = "in")
forest_V2_var
dev.off()

png('forest_V3_var.png', res = 300, width = 7.5, height = 7.5, units = "in")
forest_V3_var
dev.off()
```

```{r}
#round to 2 decimal point for our matrix
visit_1_matrix <- round(visit_1_matrix , digits = 2) 
visit_2_matrix <- round(visit_2_matrix , digits = 2) 
visit_3_matrix <- round(visit_3_matrix , digits = 2) 

```

```{r warning= FALSE}
#combine each visit matrix
new_matrix <- cbind(visit_1_matrix,
                    visit_2_matrix,
                    visit_3_matrix)
#pick only the row for body fat 
BF_matirx <- new_matrix[c(2,5,8,11),] 

#change the row names
BF_matirx <- cbind(
  c("Stress Numeric", "PSS", "Pos Mood", "Neg Mood"),
  unname(BF_matirx))

BF_matirx2 <- rbind(
  c("", "Est.", "2.5%", "97.5%"),
  c("Visit 1", "", "", ""),
  BF_matirx[, 1:4],
  c("","","",""),
  c("Visit 2", "", "", ""),
  BF_matirx[, c(1, 5:7)],
  c("","","",""),
  c("Visit 3", "", "", ""),
  BF_matirx[, c(1, 8:10)])

#forest plot for body fat
forest_BF <- forestplot(
  labeltext = BF_matirx2,
  mean = as.numeric(BF_matirx2[, 2]),
  lower = as.numeric(BF_matirx2[, 3]),
  upper = as.numeric(BF_matirx2[, 4]),
  graph.pos = "left",
  boxsize = c(0.3),
  title = "Body Fat %",
  align = c("l", "c", "c", "c"),
  graphwidth = unit(10, "cm"),
  col=fpColors(box="royalblue",
               line = "black", 
               summary = "royalblue",
               hrz_lines = "#444444"),
  txt_gp = fpTxtGp(xlab = gpar(cex = 1),
                   ticks = gpar(cex = 0.75),
                   title = gpar(cex = 2),
                   label = gpar(cex = 2),
                   summary = gpar(cex = 2)),
  hrzl_lines = list("2" = gpar(lty = 2)),
  shapes_gp = fpShapesGp(lines = gpar(lwd = 4)),
  is.summary = c(TRUE, TRUE,rep(FALSE,4), 
                 TRUE,TRUE,rep(FALSE,4), TRUE,TRUE,rep(FALSE,4)), #makes the title bold
  xlab = "RMSSD "
)
forest_BF

```

```{r warning= FALSE}
#pick only the row for body weight 
Bw_matirx <- new_matrix[c(1,4,7,10),] 

#change the row names
Bw_matirx <- cbind(
  c("Stress Numeric", "PSS", "Pos Mood", "Neg Mood"),
  unname(Bw_matirx))

Bw_matirx2 <- rbind(
  c("", "Est.", "2.5%", "97.5%"),
  c("Visit 1", "", "", ""),
  Bw_matirx[, 1:4],
  c("","","",""),
  c("Visit 2", "", "", ""),
  Bw_matirx[, c(1, 5:7)],
  c("","","",""),
  c("Visit 3", "", "", ""),
  Bw_matirx[, c(1, 8:10)])

#Body weight forest plot
forest_BW <- forestplot(
  labeltext = Bw_matirx2,
  mean = as.numeric(Bw_matirx2[, 2]),
  lower = as.numeric(Bw_matirx2[, 3]),
  upper = as.numeric(Bw_matirx2[, 4]),
  graph.pos = "left",
  boxsize = c(0.3),
  title = "Body Weight",
  align = c("l", "c", "c", "c"),
  graphwidth = unit(10, "cm"),
  col=fpColors(box="royalblue",
               line = "black", 
               summary = "royalblue",
               hrz_lines = "#444444"),
  txt_gp = fpTxtGp(xlab = gpar(cex = 1),
                   ticks = gpar(cex = 0.75),
                   title = gpar(cex = 2),
                   label = gpar(cex = 2),
                   summary = gpar(cex = 2)),
  hrzl_lines = list("2" = gpar(lty = 2)),
  shapes_gp = fpShapesGp(lines = gpar(lwd = 4)),
  is.summary = c(TRUE, TRUE,rep(FALSE,4), 
                 TRUE,TRUE,rep(FALSE,4), TRUE,TRUE,rep(FALSE,4)), #makes the title bold
  xlab = "RMSSD "
)
forest_BW

```


```{r warning=FALSE}
#Telomere length forest plor

#choose rows 3,6,9,12 for Telomere
TL_matirx <- new_matrix[c(3,6,9,12),] 

#change the row names
TL_matirx <- cbind(
  c("Stress Numeric", "PSS", "Pos Mood", "Neg Mood"),
  unname(TL_matirx))

TL_matirx2 <- rbind(
  c("", "Est.", "2.5%", "97.5%"),
  c("Visit 1", "", "", ""),
  TL_matirx[, 1:4],
  c("","","",""),
  c("Visit 2", "", "", ""),
  TL_matirx[, c(1, 5:7)],
  c("","","",""),
  c("Visit 3", "", "", ""),
  TL_matirx[, c(1, 8:10)])


forest_BW <- forestplot(
  labeltext = TL_matirx2,
  mean = as.numeric(TL_matirx2[, 2]),
  lower = as.numeric(TL_matirx2[, 3]),
  upper = as.numeric(TL_matirx2[, 4]),
  graph.pos = "left",
  boxsize = c(0.3),
  title = "Telomere Length",
  align = c("l", "c", "c", "c"),
  graphwidth = unit(10, "cm"),
  col=fpColors(box="royalblue",
               line = "black", 
               summary = "royalblue",
               hrz_lines = "#444444"),
  txt_gp = fpTxtGp(xlab = gpar(cex = 1),
                   ticks = gpar(cex = 0.75),
                   title = gpar(cex = 2),
                   label = gpar(cex = 2),
                   summary = gpar(cex = 2)),
  hrzl_lines = list("2" = gpar(lty = 2)),
  shapes_gp = fpShapesGp(lines = gpar(lwd = 4)),
  is.summary = c(TRUE, TRUE,rep(FALSE,4), 
                 TRUE,TRUE,rep(FALSE,4), TRUE,TRUE,rep(FALSE,4)), #makes the title bold
  xlab = "RMSSD "
)
forest_BW
```


```{r}
#visit 1 forest plot for RMSSD
tabletext <- cbind(c("Stress Type",row.names(visit_1_matrix)),
                   c("Mean",visit_1_matrix[,1]),
                   c("CI Lower",visit_1_matrix[,2] ),
                   c("CI Upper", visit_1_matrix[,3])) %>% 
  unname()

forest_RMSSD_01 <- forestplot(
  labeltext = (tabletext),
  mean = c(NA, visit_1_matrix[,1]),
  lower = c(NA, visit_1_matrix[,2]),
  upper = c(NA, visit_1_matrix[,3]),
  graph.pos = "left",
  boxsize = c(0.3),
  title = "Visit 1",
  align = c("l", "c", "c", "c"),
  graphwidth = unit(10, "cm"),
  col=fpColors(box="royalblue",
               line = "black", 
               summary = "royalblue",
               hrz_lines = "#444444"),
  txt_gp = fpTxtGp(xlab = gpar(cex = 1),
                   ticks = gpar(cex = 0.75),
                   title = gpar(cex = 0.75),
                   label = gpar(cex = 0.75),
                   summary = gpar(cex = 0.75)),
  hrzl_lines = list("2" = gpar(lty = 2)),
  shapes_gp = fpShapesGp(lines = gpar(lwd = 2)),
  is.summary = c(TRUE,rep(FALSE,12)), #makes the title bold
  xlab = " RMSSD"
)
forest_RMSSD_01
```

```{r}
#visit 2 forest plot for RMSSD
tabletext2 <- cbind(c("Stress Type",row.names(visit_2_matrix)),
                   c("Mean",visit_2_matrix[,1]),
                   c("CI Lower",visit_2_matrix[,2] ),
                   c("CI Upper", visit_2_matrix[,3])) %>% 
  unname()

forest_RMSSD_02 <- forestplot(
  labeltext = (tabletext2),
  mean = c(NA, visit_2_matrix[,1]),
  lower = c(NA, visit_2_matrix[,2]),
  upper = c(NA, visit_2_matrix[,3]),
  graph.pos = "left",
  boxsize = c(0.3),
  title = "Visit 2",
  align = c("l", "c", "c", "c"),
  graphwidth = unit(10, "cm"),
  col=fpColors(box="royalblue",
               line = "black", 
               summary = "royalblue",
               hrz_lines = "#444444"),
  txt_gp = fpTxtGp(xlab = gpar(cex = 1),
                   ticks = gpar(cex = 0.75),
                   title = gpar(cex = 2),
                   label = gpar(cex = 2),
                   summary = gpar(cex = 2)),
  hrzl_lines = list("2" = gpar(lty = 2)),
  shapes_gp = fpShapesGp(lines = gpar(lwd = 4)),
  is.summary = c(TRUE,rep(FALSE,12)), #makes the title bold
  xlab = " RMSSD"
  )
forest_RMSSD_02
```


```{r}
#visit 3 forets plot for RMSSD
tabletext3 <- cbind(c("Stress Type",row.names(visit_3_matrix)),
                   c("Mean",visit_3_matrix[,1]),
                   c("CI Lower",visit_3_matrix[,2] ),
                   c("CI Upper", visit_3_matrix[,3])) %>% 
  unname()

forest_RMSSD_03 <- forestplot(
  labeltext = (tabletext3),
  mean = c(NA, visit_3_matrix[,1]),
  lower = c(NA, visit_3_matrix[,2]),
  upper = c(NA, visit_3_matrix[,3]),
  graph.pos = "left",
  boxsize = c(0.3),
  title = "Visit 3",
  align = c("l", "c", "c", "c"),
  graphwidth = unit(10, "cm"),
  col=fpColors(box="royalblue",
               line = "black", 
               summary = "royalblue",
               hrz_lines = "#444444"),
  txt_gp = fpTxtGp(xlab = gpar(cex = 1),
                   ticks = gpar(cex = 0.75),
                   title = gpar(cex = 2),
                   label = gpar(cex = 2),
                   summary = gpar(cex = 2)),
  hrzl_lines = list("2" = gpar(lty = 2)),
  shapes_gp = fpShapesGp(lines = gpar(lwd = 4)),
  is.summary = c(TRUE,rep(FALSE,12)), #makes the title bold
  xlab = "RMSSD "
  )
forest_RMSSD_03
```

```{r }
#group by Id, visit, and Day and then 
#count const vs non-const in each stress type
glimpse_EMA2 <- glimpse_EMA %>% 
  group_by(Idmaternal, Trimester, Day) %>% 
  summarise(const_pos_mod = sum(abs(diff(PositiveMoodScore))),
            const_neg_mod = sum(abs(diff(NegativeMoodScore))),
            const_PSS = sum(abs(diff(PercievedStressScore))),
            const_stress_Nu = sum(abs(diff(StressedNumeric)))) %>% 
  mutate(const_pos_mod = case_when(const_pos_mod == 0 ~ 1,
                                   TRUE ~ 0),
         const_neg_mod = case_when(const_neg_mod == 0 ~ 1, 
                                   TRUE ~ 0 ),
         const_PSS = case_when(const_PSS == 0 ~ 1,
                                   TRUE ~ 0),
         const_stress_Nu = case_when(const_stress_Nu == 0 ~ 1,
                                   TRUE ~ 0))
const_glimpse_EMA <- glimpse_EMA2 %>% 
  group_by(Trimester, Day) %>% 
  summarise(n_const_pos_mod = sum(const_pos_mod),
            n_non_const_pos_mod = length(const_pos_mod) - n_const_pos_mod ,
            n_const_neg_mod = sum(const_neg_mod),
            n_non_const_neg_mod = length(const_neg_mod) - n_const_neg_mod ,
            n_const_PSS = sum(const_PSS),
            n_non_const_PSS = length(const_PSS) - n_const_PSS ,
            n_const_stress_Nu = sum(const_stress_Nu),
            n_non_const_stress_Nu = length(const_stress_Nu) - n_const_stress_Nu 
            )

const_glimpse_EMA

```

```{r}
#group our data frame by Trimester and and find the mean of them
Avg_const_glimpse_EMA <- const_glimpse_EMA %>% 
  group_by(Trimester) %>% 
  summarise(avg_const_pos_mod = mean(n_const_pos_mod),
            avg_Non_const_pos_mod = mean(n_non_const_pos_mod),
            avg_const_neg_mod = mean(n_const_neg_mod),
            avg_Non_const_neg_mod = mean(n_non_const_neg_mod),
            avg_const_PSS = mean(n_const_PSS),
            avg_Non_const_PSS = mean(n_non_const_PSS),
            avg_const_stress_Nu = mean(n_const_stress_Nu),
            avg_Non_const_stress_Nu = mean(n_non_const_stress_Nu))
Avg_const_glimpse_EMA

#pivot longer to stack them on top of each other 
pivoted_longer_avg_EMA <- Avg_const_glimpse_EMA %>%
                          pivot_longer(!Trimester,
                                       names_to = "avg_score") %>%
                          mutate(constant_status = rep(c("constant",
                                                         "not constant"),
                                                         times = 12)) %>%
                          mutate(stress_type = rep(c("numeric", "numeric",
                                                     "PSS", "PSS",
                                                     "positive", "positive",
                                                     "negative", "negative"),
                                                   times = 3)) %>%
                          subset(select = -c(2))

pivoted_longer_avg_EMA$stress_type <- factor(pivoted_longer_avg_EMA$stress_type, 
                                  levels = c("numeric", "PSS","positive","negative"))
pivoted_longer_avg_EMA

```

```{r warning= FALSE}
#change label of the plots
new_label <- c("0" = "Visit 1","1"=  "Visit 2", "2" = "Visit 3")

#bar plot for const vs non-const 
pivoted_longer_avg_EMA2 <- pivoted_longer_avg_EMA %>%
  ggplot(aes(x =pivoted_longer_avg_EMA$stress_type,y = value, fill = constant_status)) +
  geom_col(stat = "identity")+
  theme_bw()+
  ggtitle("Constant vs Non-Constant In Different Stress Type")+
  xlab("Stress Type")+
  ylab("Value")+
  theme(plot.title = element_text(size = 28, face = "bold"), 
        plot.subtitle=element_text(size = 13),
        axis.text.x = element_text(angle = 90,hjust = 0.5,size = 25),
        axis.text.y = element_text(size = 20),
        axis.text=element_text(size=12,face="bold"),
        axis.title=element_text(size=30,face="bold"),
        legend.title = element_text(size = 20, face = "bold"),
        legend.text = element_text(size = 20),
        axis.title.x = element_text(vjust=0.25),
        strip.text = element_text(size = 25, margin = margin()),
        strip.background = element_rect(fill="lightblue", size=1, color="darkblue"))+
  scale_fill_discrete(name = "Constant Status")+
  facet_wrap(~Trimester, scales = "free_x" , labeller = labeller(Trimester = new_label))
pivoted_longer_avg_EMA2
```
